id: P32137138
initial_creation_type: input
source_metadata:
  title: Pramāṇavārttikaṭīkā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Klaus Wille
  contribution to GRETIL: Klaus Wille
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:22:10.565621'
last_modified_at: '2022-03-09T15:22:10.565639'
